export default{
    name:"Salar Sotude Maram",
    home:"HOME",
    about:"ABOUT",
    resume:"RESUME",
    portfolios:"PORTFOLIOS",
    contact:"CONTACT",
    hi:"Hi,I am",
    body2:" Salar Sotude Maram",
    hi2:"",
    desc:"I'm frontend developer.I can provide clean code and pixel perfect design.I also make websites more and more atractive with web animations.",
    aboutme:"ABOUT ME",
    services:"Services",
    fullname:"FullName",
    age:"Age",
    nationality:"Nationality",
    nation:"Iranian",
    language:"Languages",
    dil:"English , Persian",
    phone:"Phone",
    downloadcv:"Download Cv",
    webDesign:"web Design",
    webDevelopment:"web Development",
    mobileApplication:"Mobile Application",
    descService:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    MySkills:"MY SKILLS",
    WorkingExperience:"Working Experiences",
    EducationalQualifications:"Educational Qualifications",
    workingSteps:[{id:-1,date:"",title:"",subtitle:"",content:""},
             {id:1,date:"2022-2023",title:"Frontend Web Developer",subtitle:"abc University",content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
             {id:2,date:"2015-2016",title:"Micro controller Programmer",subtitle:"abc University",content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
             {id:-2,date:"",title:"",subtitle:"",content:""}],
    educationalSteps:[{id:-1,date:"",title:"",subtitle:"",content:""},
             {id:1,date:"2018-2021",title:"Master Of Science",subtitle:"Shahid Beheshti University",content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
             {id:2,date:"2013-2018",title:"Bachelor of science",subtitle:"Urmia University of Technology",content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},
             {id:-2,date:"",title:"",subtitle:"",content:""}],
    Contactme:"CONTACT ME",
    getintouch:"Get In Touch",
    Name:"Enter your Name",
    Email:"Enter your email",
    subject:"Enter your subject",
    message:"Enter your Message",
    sendmessage:"Send Message",
    email:"email",
    address:"Address",
    addressdetail:"Urmia,Shahrak Isar",
 portfoliosList:[{id:1,title:"React developer",desc:"React Teacher",image:"https://www.datocms-assets.com/45470/1631110818-logo-react-js.png"},
{id:2,title:"React developer",desc:"React Teacher",image:"https://www.datocms-assets.com/45470/1631110818-logo-react-js.png"},
{id:3,title:"React developer",desc:"React Teacher",image:"https://www.datocms-assets.com/45470/1631110818-logo-react-js.png"},
{id:4,title:"React developer",desc:"React Teacher",image:"https://www.datocms-assets.com/45470/1631110818-logo-react-js.png"},
{id:5,title:"React developer",desc:"React Teacher",image:"https://www.datocms-assets.com/45470/1631110818-logo-react-js.png"},]
}
